### Part 1: Theory

1. **Definition of a Symmetric Matrix**  
A square matrix $A$ is called **symmetric** if $A = A^T$.
This means that for every ${i}$ and ${j}$, the element $\alpha_{ij} = a_{ji}$.

2. **Definitions of Eigenvalues and Eigenvectors**  
For a square matrix $A$, a scalar $\lambda$ and a nonzero vector $v$ form an eigenpair if $A v = \lambda v$.  
Here, $\lambda$ is called an **eigenvalue** and $v$ is its corresponding **eigenvector**.

3. **What is a Singular Matrix?**  
A matrix is **singular** if it is not invertible. Equivalently, a square matrix $A$ is singular if $\det(A) = 0$, or if its rows (or columns) are linearly dependent.

4. **Positive Definite and Positive Semi-Definite Matrices**  
- A symmetric matrix $A$ is **positive definite** if for every nonzero vector $x$, $x^T A x > 0$.  
- It is **positive semi-definite** if for every vector $x$, $x^T A x \ge 0$.

5. **Proof that \(A = M^T M\) is Positive Definite**  
Let $M$ be a nonsingular matrix, and define $A = M^T M$. For any nonzero vector $x$:

$$
x^T A x = x^T (M^T M) x = (Mx)^T (Mx) = \|Mx\|^2.
$$
Since $M$ is nonsingular, $\|Mx\|^2 > 0$ whenever $x \neq 0$. Hence, $A$ is positive definite.

### Part 2: Programming Problem

This notebook implements the required tasks using the NumPy library. The steps include creating vectors and matrices, verifying symmetry, solving linear systems, and checking the results.

In [2]:
import numpy as np

In [3]:
# Point 1: Created vector b and printed it.
b = np.array([-3, -8, 7])
print("Vector b:")
print(b)

Vector b:
[-3 -8  7]


In [4]:
# Point 2: Created matrix A and printed it.
A = np.array([[-10,  3, 11],
              [  3, -5, -4],
              [ 11, -4, -7]])
print("\nMatrix A:")
print(A)


Matrix A:
[[-10   3  11]
 [  3  -5  -4]
 [ 11  -4  -7]]


In [5]:
# Point 3: Checked if matrix A is symmetric.
is_symmetric = np.allclose(A, A.T)
print("\nIs matrix A symmetric?", is_symmetric)


Is matrix A symmetric? True


In [6]:
# Point 4: Solved the linear system A*x = b.
x = np.linalg.solve(A, b)
print("\nSolution x for A*x = b:")
print(x)


Solution x for A*x = b:
[2. 2. 1.]


In [7]:
# Point 5: Computed r = A*x to verify the solution.
r = A.dot(x)
print("\nProduct A*x (r):")
print(r)


Product A*x (r):
[-3. -8.  7.]


In [8]:
# Point 6: Computed the norm of (A*x - b).
norm_diff = np.linalg.norm(r - b)
print("\nNorm of (A*x - b):", norm_diff)
print("The norm should be near zero (any small value is due to floating point precision).")


Norm of (A*x - b): 3.972054645195637e-15
The norm should be near zero (any small value is due to floating point precision).


In [9]:
# Point 7: Computed the determinant of A.
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)


Determinant of A: 214.0000000000001


In [10]:
# Point 8: Defined matrix A1 and repeated the process.
A1 = np.array([[-1,    3000,    1],
               [2000,  -1.5,   -2.5],
               [-1999, -2998.5, 1.5]])
print("\nMatrix A1:")
print(A1)

# Checked if A1 is symmetric.
is_symmetric_A1 = np.allclose(A1, A1.T)
print("\nIs matrix A1 symmetric?", is_symmetric_A1)

# Solved the linear system A1*x1 = b.
try:
    x1 = np.linalg.solve(A1, b)
    print("\nSolution x1 for A1*x1 = b:")
    print(x1)
except np.linalg.LinAlgError as e:
    print("\nMatrix A1 is singular or ill-conditioned. Error:", e)

# Verified the solution (if computed) by computing r1 = A1*x1.
try:
    r1 = A1.dot(x1)
    print("\nProduct A1*x1 (r1):")
    print(r1)
    
    # Computed the norm of (A1*x1 - b).
    norm_diff_A1 = np.linalg.norm(r1 - b)
    print("\nNorm of (A1*x1 - b):", norm_diff_A1)
except NameError:
    print("Skipping product and norm calculation for A1 because the system could not be solved.")

# Computed the determinant of A1.
det_A1 = np.linalg.det(A1)
print("\nDeterminant of A1:", det_A1)

print("\nObservation:")
print("1. Matrix A1 is not symmetric (off-diagonal elements differ).")
print("2. The determinant is nearly zero, indicating that A1 is nearly singular or ill-conditioned.")
print("3. This ill-conditioning may cause numerical instability when solving A1*x1 = b.")



Matrix A1:
[[-1.0000e+00  3.0000e+03  1.0000e+00]
 [ 2.0000e+03 -1.5000e+00 -2.5000e+00]
 [-1.9990e+03 -2.9985e+03  1.5000e+00]]

Is matrix A1 symmetric? False

Solution x1 for A1*x1 = b:
[ 2.25135002e+13 -5.99729500e+12  1.80143985e+16]

Product A1*x1 (r1):
[-4. -8.  8.]

Norm of (A1*x1 - b): 1.4142135623730951

Determinant of A1: 1.3322672964832825e-09

Observation:
1. Matrix A1 is not symmetric (off-diagonal elements differ).
2. The determinant is nearly zero, indicating that A1 is nearly singular or ill-conditioned.
3. This ill-conditioning may cause numerical instability when solving A1*x1 = b.
